name: Build homeproxy for OpenWrt (ipq60xx/generic)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET: ipq60xx/generic
      ARCH: aarch64_cortex-a53_neon-vfpv4

    steps:
      - name: Checkout OpenWrt source (LiBwrt/openwrt-6.x)
        uses: actions/checkout@v4
        with:
          repository: LiBwrt/openwrt-6.x
          ref: main

      - name: Add homeproxy package
        run: |
          git clone https://github.com/immortalwrt/homeproxy package/homeproxy

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure target
        run: |
          # Указываем таргет ipq60xx/generic
          echo "CONFIG_TARGET_ipq60xx=y" >> .config
          echo "CONFIG_TARGET_ipq60xx_generic=y" >> .config
          make defconfig

      - name: Build homeproxy package
        run: |
          make package/homeproxy/compile V=s -j$(nproc)

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: homeproxy-ipk-${{ env.TARGET }}
          path: bin/packages/${{ env.ARCH }}/base/homeproxy*.ipk
