name: Build homeproxy with LiBwrt/openwrt-6.x (ipq60xx/generic)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET: ipq60xx/generic

    steps:
      - name: Checkout LiBwrt/openwrt-6.x
        uses: actions/checkout@v3
        with:
          repository: LiBwrt/openwrt-6.x
          # Можно указать branch, если нужно
          ref: main

      - name: Checkout homeproxy package
        # Клонируем пакет homeproxy в папку package/homeproxy
        run: |
          git clone https://github.com/immortalwrt/homeproxy package/homeproxy

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure target
        run: |
          # Устанавливаем нужные опции в .config, чтобы включить ipq60xx generic
          # В зависимости от структуры config: может быть TARGET_ipq60xx=y и TARGET_ipq60xx_generic=y
          ./scripts/feeds update -a
          make defconfig
          # Опционально: можно использовать scripts/config или `yes '' | make menuconfig` с автоответами

      - name: Build homeproxy package
        run: |
          make package/homeproxy/compile V=s -j$(nproc)

      - name: Gather artifact
        uses: actions/upload-artifact@v3
        with:
          name: homeproxy-ipk-${{ env.TARGET }}
          path: bin/packages/${{ env.TARGET##*/ }}/base/homeproxy*.ipk
